name: main branch builder
on:
  pull_request:
      branches: [ "main" ]
  push:

  # allow manual runs too
  workflow_dispatch:
    inputs:
      force_breaking:
        type: boolean
        description: 'TODO - force codegen even with breaking changes'
        required: false
        default: false

jobs:
  check-for-breaking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v0.5.0
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/${{ github.repository }}.git#branch=main'

  gen-csharp:
    runs-on: ubuntu-latest
    needs: [check-for-breaking]
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: |
          dotnet new tool-manifest
          dotnet tool install --local protobuf-net.Protogen --version 3.1.17
      - name: generate csharp code
        run: dotnet tool run protogen --csharp_out=./generated/csharp *.proto
            # Commit and push all changed files.
      - name: git commit generated code
        # only run on main branch push (after pull request merged)
        if: github.event_name == 'push'
        run: |
          git config --global user.name "autocommit"
          git config --global user.email "autocommit@noreply.redhat.com"
          git add ./generated/csharp
          git commit --allow-empty -a -m "autocommit from CI job"
          git push
