name: all branch linter
on:
  pull_request:
      types: [opened, reopened]
      branches: [ "main" ]

  # allow manual runs too
  workflow_dispatch:

jobs:
  lint-the-proto-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
