name: main branch linter
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

  # allow manual runs too
  workflow_dispatch:

jobs:
  lint-the-proto-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v0.5.0
      - uses: bufbuild/buf-lint-action@v1
